"""empty message

Revision ID: 494e467c8673
Revises: 71f2f96f39f2
Create Date: 2024-03-07 01:30:37.823826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494e467c8673'
down_revision = '71f2f96f39f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
